---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: crypto
spec:
  ports:
  - nodePort: 30306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
  type: NodePort