---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: crypto
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.4
        name: mariadb
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ROOTPASSWORD
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: gs-ebs-claim