---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crypto
  name: crypto-deployment
spec:
  selector:
    matchLabels:
      app: crypto-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: crypto-deployment
    spec:
      containers:
      - image: 603229842386.dkr.ecr.ap-southeast-2.amazonaws.com/gs-cryptproject:latest
        imagePullPolicy: Always
        name: crypto-deployment
        ports:
        - containerPort: 8080
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY