apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gs-gp3
# allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp3
  allowAutoIOPSPerGBIncrease: 'true'
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values:
    - ap-southeast-2a
    - ap-southeast-2c